
spring.ai.ollama.base-url=http://localhost:11434

## ???????????? ???????????? (2+ ???, ?? ?????? ??????? ???????????)
spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL:qwen3:8b}

## ??????? ???????????? ?????? (20-30 ???, ?? ????? ??????? ???????????)
#spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL:llama3.1:8b}
app.agent.experiment.enabled=true

# AI Models
OLLAMA_CHAT_MODEL=qwen3:8b
# Search Tools
TAVILY_API_KEY=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
NEWSAPI_KEY=92c1479e7fb2462da0d5ab08d52f859f
ALPHAVANTAGE_KEY=QHP6ED8SZKI10LX9